services:
  # backend:
  #   build: 
  #     dockerfile: ./Dockerfile
  #   command: 
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   # volumes:
  #   #   - 
  #   # networks:
  #   #   - backend
  #   env_file:
  #     - ./.env
  #   depends_on: 
  #     - postgres

  air:
    image: cosmtrek/air
    working_dir: /go/src
    command: air
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    depends_on: 
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  # networks:
  #   - backend

volumes:
  postgres_data:

# networks:
#   backend:
#     driver: bridge
#     #?