services:
  backend:
    build: 
      dockerfile: ./Dockerfile
    command: go test
    restart: unless-stopped
    environment:
      - POSTGRES_DB='test_back'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on: 
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB='test_back'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./testdata/mockdata.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: