services:
  app:
    build: 
      dockerfile: ./Dockerfile
    command: 
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - 
    env_file:
      - ./.env
    depends_on: postgres

  postgres:
    image: postgres:17.2
    restart: always
    env_file: 
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: